# PROJECT-When Was the Golden Age of Video Games?
<p>In this project, I am analyzing video game critic and user scores as well as sales data for the top 400 video games released since 1977. Finding golden age of video games by identifying release years that users and critics liked best, and also explore the business side of gaming by looking at game sales data.</p>
<p>SKILL USED: This involves joining datasets and comparing results with set theory. Also filter, group, and order data. </p>

## Table of Contents:
1. <code>The ten best-selling video games</code>
2. <code>Finding Missing review scores</code>
3. <code>Years that video game critics loved</code>
4. <code>Was 1982 really that great?</code>
5. <code>Years that dropped off the critics' favorites list</code>
6. <code>Years video game players loved</code>
7. <code>Years that both players and critics loved</code>
8. <code>Sales in the best video game years</code>
9. <code>Summary </code>

## 1. The ten best-selling video games

<p>Video games are big business: the global gaming market is projected to be worth more than $300 billion by 2027 according to <a href="https://www.mordorintelligence.com/industry-reports/global-gaming-market">Mordor Intelligence</a>.</p>
<p>In this project,exploring the top 400 best-selling video games created between 1977 and 2020. We'll compare a dataset on game sales with critic and user reviews to determine whether or not video games have improved as the gaming market has grown.</p>
<p>Our database contains two tables. Find the complete dataset with over 13,000 games on <a href="https://www.kaggle.com/holmjason2/videogamedata">Kaggle</a>. </p>
<h3 id="game_sales"><code>game_sales</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>game</code></td>
<td>varchar</td>
<td>Name of the video game</td>
</tr>
<tr>
<td style="text-align:left;"><code>platform</code></td>
<td>varchar</td>
<td>Gaming platform</td>
</tr>
<tr>
<td style="text-align:left;"><code>publisher</code></td>
<td>varchar</td>
<td>Game publisher</td>
</tr>
<tr>
<td style="text-align:left;"><code>developer</code></td>
<td>varchar</td>
<td>Game developer</td>
</tr>
<tr>
<td style="text-align:left;"><code>games_sold</code></td>
<td>float</td>
<td>Number of copies sold (millions)</td>
</tr>
<tr>
<td style="text-align:left;"><code>year</code></td>
<td>int</td>
<td>Release year</td>
</tr>
</tbody>
</table>
<h3 id="reviews"><code>reviews</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>game</code></td>
<td>varchar</td>
<td>Name of the video game</td>
</tr>
<tr>
<td style="text-align:left;"><code>critic_score</code></td>
<td>float</td>
<td>Critic score according to Metacritic</td>
</tr>
<tr>
<td style="text-align:left;"><code>user_score</code></td>
<td>float</td>
<td>User score according to Metacritic</td>
</tr>
</tbody>
</table>
<p>Let's begin by looking at some of the top selling video games of all time!</p>

In [61]:
%%sql
postgresql:///games

SELECT * FROM game_sales
ORDER BY games_sold DESC
limit 10;

10 rows affected.

[('Wii Sports for Wii', 'Wii', 'Nintendo', 'Nintendo EAD', Decimal('82.90'), 2006),
 ('Super Mario Bros. for NES', 'NES', 'Nintendo', 'Nintendo EAD', Decimal('40.24'), 1985),
 ('Counter-Strike: Global Offensive for PC', 'PC', 'Valve', 'Valve Corporation', Decimal('40.00'), 2012),
 ('Mario Kart Wii for Wii', 'Wii', 'Nintendo', 'Nintendo EAD', Decimal('37.32'), 2008),
 ("PLAYERUNKNOWN'S BATTLEGROUNDS for PC", 'PC', 'PUBG Corporation', 'PUBG Corporation', Decimal('36.60'), 2017),
 ('Minecraft for PC', 'PC', 'Mojang', 'Mojang AB', Decimal('33.15'), 2010),
 ('Wii Sports Resort for Wii', 'Wii', 'Nintendo', 'Nintendo EAD', Decimal('33.13'), 2009),
 ('Pokemon Red / Green / Blue Version for GB', 'GB', 'Nintendo', 'Game Freak', Decimal('31.38'), 1998),
 ('New Super Mario Bros. for DS', 'DS', 'Nintendo', 'Nintendo EAD', Decimal('30.80'), 2006),
 ('New Super Mario Bros. Wii for Wii', 'Wii', 'Nintendo', 'Nintendo EAD', Decimal('30.30'), 2009)]

<p><code>INFERENCE:</code><p>The best-selling video games were released between 1985 to 2017! That's quite a range; So, using data from the <code>reviews</code> table to gain more insight on the best years for video games. </p>

## 2. Missing review scores

<p>First, it's important to explore the limitations of the database. One big shortcoming is that there is not any <code>reviews</code> data for some of the games on the <code>game_sales</code> table. </p>

In [63]:
%%sql 

-- Join games_sales and reviews
-- Select a count of the number of games where both critic_score and user_score are null

SELECT COUNT(*)
FROM game_sales g
LEFT JOIN reviews r ON g.game=r.game
WHERE critic_score IS NULL AND user_score IS NULL ;

 * postgresql:///games
1 rows affected.

[(31,)]

<p><code>INFERENCE:</code><p>It looks like a little less than ten percent of the games on the <code>game_sales</code> table don't have any reviews data. That's a small enough percentage.So,continuing exploration.</p>

## 3. Years that video game critics loved

<p>There are lots of ways to measure the best years for video games!  starting with what the critics think. </p>

In [65]:
%%sql

-- Select release year and average critic score for each year, rounded and aliased
-- Join the game_sales and reviews tables
-- Group by release year
-- Order the data from highest to lowest avg_critic_score and limit to 10 results

SELECT year, ROUND(AVG(critic_score),2) AS avg_critic_score
FROM game_sales g
JOIN reviews r ON g.game=r.game
GROUP BY year
ORDER BY avg_critic_score DESC
LIMIT 10;

 * postgresql:///games
10 rows affected.

[(1990, Decimal('9.80')),
 (1992, Decimal('9.67')),
 (1998, Decimal('9.32')),
 (2020, Decimal('9.20')),
 (1993, Decimal('9.10')),
 (1995, Decimal('9.07')),
 (2004, Decimal('9.03')),
 (1982, Decimal('9.00')),
 (2002, Decimal('8.99')),
 (1999, Decimal('8.93'))]

<p><code>INFERENCE:</code><p>The range of great years according to critic reviews goes from 1982 until 2020. </p><p>Some of those <code>avg_critic_score</code> values look like suspiciously round numbers for averages. The value for 1982 looks especially fishy. </p>

## 4. Was 1982 really that great?


<p>So, finding out whether 1982 really was such a great year for video games.</p>

In [67]:
%%sql 

-- Paste your query from the previous task; update it to add a count of games released in each year called num_games
-- Update the query so that it only returns years that have more than four reviewed games


SELECT year, ROUND(AVG(critic_score),2) AS avg_critic_score, COUNT(*) AS num_games
FROM game_sales g
JOIN reviews r ON g.game=r.game
GROUP BY year
HAVING COUNT(*)>4
ORDER BY avg_critic_score DESC
LIMIT 10;

 * postgresql:///games
10 rows affected.

[(1998, Decimal('9.32'), 10),
 (2004, Decimal('9.03'), 11),
 (2002, Decimal('8.99'), 9),
 (1999, Decimal('8.93'), 11),
 (2001, Decimal('8.82'), 13),
 (2011, Decimal('8.76'), 26),
 (2016, Decimal('8.67'), 13),
 (2013, Decimal('8.66'), 18),
 (2008, Decimal('8.63'), 20),
 (2012, Decimal('8.62'), 12)]

<p><code>INFERENCE:</code><p>The <code>num_games</code> column tells that the new list of the critics' top games reflects years that had quite a few well-reviewed games rather than just one or two hits. </p>
<p>Identifying which years dropped off the list due to having four or fewer reviewed games?  </p>

## 5. Years that dropped off the critics' favorites list


<h3 id="top_critic_years"><code>top_critic_years</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>year</code></td>
<td>int</td>
<td>Year of video game release</td>
</tr>
<tr>
<td style="text-align:left;"><code>avg_critic_score</code></td>
<td>float</td>
<td>Average of all critic scores for games released in that year</td>
</tr>
</tbody>
</table>
<h3 id="top_critic_years_more_than_four_games"><code>top_critic_years_more_than_four_games</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>year</code></td>
<td>int</td>
<td>Year of video game release</td>
</tr>
<tr>
<td style="text-align:left;"><code>num_games</code></td>
<td>int</td>
<td>Count of the number of video games released in that year</td>
</tr>
<tr>
<td style="text-align:left;"><code>avg_critic_score</code></td>
<td>float</td>
<td>Average of all critic scores for games released in that year</td>
</tr>
</tbody>
</table>

In [69]:
%%sql 
postgresql:///games

SELECT year,avg_critic_score
FROM top_critic_years
EXCEPT
SELECT year,avg_critic_score
FROM top_critic_years_more_than_four_games
ORDER BY avg_critic_score DESC;

6 rows affected.

[(1990, Decimal('9.80')),
 (1992, Decimal('9.67')),
 (2020, Decimal('9.20')),
 (1993, Decimal('9.10')),
 (1995, Decimal('9.07')),
 (1982, Decimal('9.00'))]

<p><code>INFERENCE:</code><p>It looks like the early 1990s might merit consideration as the golden age of video games based on <code>critic_score</code> alone, but  need to gather more games and reviews data to do further analysis. </p>

## 6. Years video game players loved

<p>Moving on to looking at the opinions of another important group of people: players!</p>

In [71]:
%%sql 

-- Select year, an average of user_score, and a count of games released in a given year, aliased and rounded
-- Include only years with more than four reviewed games; group data by year
-- Order data by avg_user_score, and limit to ten results

SELECT year, ROUND(AVG(user_score),2) AS avg_user_score, COUNT(*) AS num_games
FROM game_sales g
JOIN reviews r ON g.game=r.game
GROUP BY year
HAVING COUNT(*)>4
ORDER BY avg_user_score DESC
LIMIT 10;

 * postgresql:///games
10 rows affected.

[(1997, Decimal('9.50'), 8),
 (1998, Decimal('9.40'), 10),
 (2010, Decimal('9.24'), 23),
 (2009, Decimal('9.18'), 20),
 (2008, Decimal('9.03'), 20),
 (1996, Decimal('9.00'), 5),
 (2005, Decimal('8.95'), 13),
 (2006, Decimal('8.95'), 16),
 (2000, Decimal('8.80'), 8),
 (1999, Decimal('8.80'), 11)]

## 7. Years that both players and critics loved

<h3 id="top_critic_years_more_than_four_games"><code>top_critic_years_more_than_four_games</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>year</code></td>
<td>int</td>
<td>Year of video game release</td>
</tr>
<tr>
<td style="text-align:left;"><code>num_games</code></td>
<td>int</td>
<td>Count of the number of video games released in that year</td>
</tr>
<tr>
<td style="text-align:left;"><code>avg_critic_score</code></td>
<td>float</td>
<td>Average of all critic scores for games released in that year</td>
</tr>
</tbody>
</table>
<p>We've also saved the results of our top user years query from the previous task into a table:</p>
<h3 id="top_user_years_more_than_four_games"><code>top_user_years_more_than_four_games</code></h3>
<table>
<thead>
<tr>
<th style="text-align:left;">column</th>
<th>type</th>
<th>meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"><code>year</code></td>
<td>int</td>
<td>Year of video game release</td>
</tr>
<tr>
<td style="text-align:left;"><code>num_games</code></td>
<td>int</td>
<td>Count of the number of video games released in that year</td>
</tr>
<tr>
<td style="text-align:left;"><code>avg_user_score</code></td>
<td>float</td>
<td>Average of all user scores for games released in that year</td>
</tr>
</tbody>
</table>

In [73]:
%%sql 

-- Select the year results that appear on both tables

SELECT tu.year
FROM top_critic_years_more_than_four_games tc
INNER JOIN top_user_years_more_than_four_games tu
ON tc.year=tu.year;

 * postgresql:///games
3 rows affected.

[(1998,), (2002,), (2008,)]

<p><code>INFERENCE:</code><p>Looks like there are three years that both users and critics agreed were in the top ten! </p>

## 8. Sales in the best video game years

In [75]:
%%sql 

-- Select year and sum of games_sold, aliased as total_games_sold; order results by total_games_sold descending
-- Filter game_sales based on whether each year is in the list returned in the previous task

SELECT year, SUM(games_sold) AS total_games_sold
FROM game_sales
WHERE year IN( SELECT tu.year
FROM top_critic_years_more_than_four_games tc
INNER JOIN top_user_years_more_than_four_games tu
ON tc.year=tu.year )
GROUP BY year
ORDER BY total_games_sold DESC;

 * postgresql:///games
3 rows affected.

[(2008, Decimal('175.07')),
 (1998, Decimal('101.52')),
 (2002, Decimal('58.67'))]

<p><code>INFERENCE:</code><p>Identified the  best video game sale years</p>